version: '2'

services:
 cas1:
    container_name: cas1
    image: cassandra:latest
    volumes:
      - D:\studia\semestr_7\niereleacyjne_bazy_danych\zadanie_4\databases\data\node1:/var/lib/cassandra/data
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
 cas2:
  container_name: cas2
  image: cassandra:latest
  volumes:
      - D:\studia\semestr_7\niereleacyjne_bazy_danych\zadanie_4\databases\data\node2:/var/lib/cassandra/data
  ports:
      - 9043:9042
  depends_on:
    - cas1
  environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_SEEDS=cas1